const ibaadatDataBase = [
  {
    id: "I001",
    title: "St. Stephen's Church",
    category: "Duet",
    position: "Winner",
    streamLink: `https://www.youtube.com/embed/8ah0knBja10?si=TwqIshWsRTmQLxuf`,
    downloadPath: `https://drive.google.com/file/d/1Ga_64CDDtkJj41xf-3G4367m3FpGap6k/view?usp=drive_link`,
  },
  {
    id: "I002",
    title: "Green Park Free Church",
    category: "Duet",
    position: "Runner-up",
    streamLink: `https://www.youtube.com/embed/h7jCRmAhFgU?si=4U4_ukjJE_kUdeUC`,
    downloadPath: `https://drive.google.com/file/d/1f86zSCHGQCAiixtYxKeVU0k3mcLwhKIq/view?usp=drive_link`,
  },
  {
    id: "I003",
    title: "Jehowah Jireh Band",
    category: "Duet",
    position: "2nd Runner-up",
    streamLink: `https://www.youtube.com/embed/3W7VFlNQs_k?si=a7X247sK5Imq43Qp`,
    downloadPath: `https://drive.google.com/file/d/1Sdcp_fOwLoHYlC3HRHK2nJviM7SbBCzq/view?usp=drive_link`,
  },
  {
    id: "I004",
    title: "St. Anthony's Church",
    category: "Duet",
    position: "--",
    streamLink: `https://www.youtube.com/embed/wxlwD0BM_U4?si=cKGYFkgSEhxRBWwv`,
    downloadPath: `https://drive.google.com/file/d/1aRPevjLuPVtL3mRlNOjKXKm1JQorzplO/view?usp=drive_link`,
  },
  {
    id: "I005",
    title: "Prabhu Prakash Sadan Church",
    category: "Qawwali",
    position: "Winner",
    streamLink: `https://www.youtube.com/embed/zPDXl9Q3Ykw?si=fD7mi2_Ipou456Ah`,
    downloadPath: `https://drive.google.com/file/d/1efwGLsfNUEmkVdwF51zEuEfo2cfj_56M/view?usp=drive_link`,
  },
  {
    id: "I006",
    title: "Jehowah Jireh Band",
    category: "Qawwali",
    position: "Runner-up",
    streamLink: `https://www.youtube.com/embed/YjR7iBSLm7E?si=-XCFodHpUKsbY2ay`,
    downloadPath: `https://drive.google.com/file/d/1uZk01GglHd-razsz0KCxGT6JISUDNdUx/view?usp=drive_link`,
  },
  {
    id: "I007",
    title: "CNI Church - Santokh Majra",
    category: "Qawwali",
    position: "2nd Runner-up",
    streamLink: `https://www.youtube.com/embed/QFn5QUoucnI?si=5j3BkWkSDvisBExZ`,
    downloadPath: `https://drive.google.com/file/d/1eX0MEfdFHuYeglM8qGMocq15RPLLOSTE/view?usp=drive_link`,
  },
  {
    id: "I008",
    title: "Green Park Free Church",
    category: "Qawwali",
    position: "--",
    streamLink: `https://www.youtube.com/embed/BGMQu2P0tYg?si=fL1Mu1rgehWJ4GN3`,
    downloadPath: `https://drive.google.com/file/d/1ElhMssFRP-5Y0PZhkpridN28jhLilLMt/view?usp=sharing`,
  },
  {
    id: "I009",
    title: "SFC Youth Fellowship",
    category: `"Qawwali" - Special Performance`,
    position: "Non-Competitive",
    streamLink: `https://www.youtube.com/embed/GMSLBAv8o30?si=2T6H4bhwD9Y05tRP`,
    downloadPath: `https://drive.google.com/file/d/1jWdT6PSzAuzvaeR-Pa3bIPP6_HU4t6DX/view?usp=drive_link`,
  },
  {
    id: "I0010",
    title: "Mr. Sunny Samson (Event Judge)",
    category: `"Qawwali" - Special Performance`,
    position: "Non-Competitive",
    streamLink: `https://www.youtube.com/embed/nNTB6DN_Zrg?si=HF0MFUjvZ0p-2hQq`,
    downloadPath: `https://drive.google.com/file/d/1CsAt5xQGB7eqGP85XVIx3kZC4zbcFfJ7/view?usp=drive_link`,
  },
  {
    id: "I0011",
    title: "Mr. Marshall Henry (SFC)",
    category: `"Solo" - Special Performance`,
    position: "Non-Competitive",
    streamLink: `https://www.youtube.com/embed/GEki1G20E4M?si=XuxnY-tnC7nVcRhb`,
    downloadPath: `https://drive.google.com/file/d/1hQRRL9OYl6RHS9IvXzOG-hcAPJHbc5Ko/view?usp=drive_link`,
  },
  {
    id: "I0012",
    title: "SFC Sunday School Kids",
    category: `"Group Song" - Special Performance`,
    position: "Non-Competitive",
    streamLink: `https://www.youtube.com/embed/Q43X1wJRdvE?si=PPK_XOybunl2z1ND`,
    downloadPath: `https://drive.google.com/file/d/1IQGIEu7j5ICbtdCpf04yh6OyyxA2iHBB/view?usp=drive_link`,
  },
];

export default ibaadatDataBase;
